-- Logic
Tracker:AddLocations("locations/apple_market.jsonc")
Tracker:AddLocations("locations/cardon_forest_subgate.jsonc")
Tracker:AddLocations("locations/cardon_forest.jsonc")
Tracker:AddLocations("locations/city_hall.jsonc")
Tracker:AddLocations("locations/clozer_woods_subgate.jsonc")
Tracker:AddLocations("locations/clozer_woods.jsonc")
Tracker:AddLocations("locations/downtown.jsonc")
Tracker:AddLocations("locations/lake_jyun_subgate.jsonc")
Tracker:AddLocations("locations/lake_jyun.jsonc")
Tracker:AddLocations("locations/main_gate.jsonc")
Tracker:AddLocations("locations/ocean_tower.jsonc")
Tracker:AddLocations("locations/old_city.jsonc")
Tracker:AddLocations("locations/support_car.jsonc")
Tracker:AddLocations("locations/underground_ruins.jsonc")
Tracker:AddLocations("locations/uptown.jsonc")
Tracker:AddLocations("locations/yass_plains.jsonc")
